version: '3'
services:
  jenkins:
    container_name: jenkins-docker
    image: nithinbs18/jenkins-docker
    build:
      context: custom
    # ports:
    #   - "8080:8080"
    environment:
      VIRTUAL_HOST: ci.digitalcitadel.tech
      VIRTUAL_PORT: '8080'
      # LETSENCRYPT_HOST: ci.digitalcitadel.tech
      # LETSENCRYPT_EMAIL: info.digitalcitadel@gmail.com
    volumes:
      - "/root/jenkins/:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
  default:
    external:
      name: webproxy

